-- |
--
-- Module      : GHCTL.RepositoriesYamlSpec
-- Copyright   : (c) 2025 Patrick Brisbin
-- License     : AGPL-3
-- Maintainer  : pbrisbin@gmail.com
-- Stability   : experimental
-- Portability : POSIX
module GHCTL.RepositoriesYamlSpec
  ( spec
  ) where

import GHCTL.Prelude

import GHCTL.App
import GHCTL.RepositoriesYaml
import Test.Hspec

spec :: Spec
spec = do
  describe "getCurrentRepositoriesYaml" $ do
    it "parses all my own repositories without error" $ example $ do
      pendingWith "Only enable this when working on parsing"
      void
        $ runAppM
        $ getCurrentRepositoriesYaml
          [ "pbrisbin/ghctl"
          , "pbrisbin/semantic-release-stack-upload"
          , "pbrisbin/setup-tool-action"
          , "pbrisbin/dotfiles"
          , "pbrisbin/hs-shellwords"
          , "pbrisbin/indirect"
          , "pbrisbin/arch-setup"
          , "pbrisbin/amazonka-contrib-s3-sync"
          , "pbrisbin/git-save-all"
          , "pbrisbin/bugsnag-haskell"
          , "pbrisbin/yaml-marked"
          , "pbrisbin/escaped"
          , "pbrisbin/vbump"
          , "pbrisbin/ronn"
          , "pbrisbin/pbrisbin.com-hugo"
          , "pbrisbin/r2cl"
          , "pbrisbin/yesod-paginator"
          , "pbrisbin/aws-ssm-rename"
          , "pbrisbin/stack-tools"
          , "pbrisbin/thesmallestyesodapp.com"
          , "pbrisbin/coverish"
          , "pbrisbin/litx"
          , "pbrisbin/brisb.in"
          , "pbrisbin/tee-io"
          , "pbrisbin/passphrase.me"
          , "pbrisbin/stack-ls-snapshots"
          , "pbrisbin/aur-release"
          , "pbrisbin/gravatar"
          , "pbrisbin/aurget"
          , "pbrisbin/msu"
          , "pbrisbin/vim-colors-off"
          , "pbrisbin/drync"
          , "pbrisbin/google-oauth2"
          , "pbrisbin/stack-upload-action"
          , "pbrisbin/aws-ecs-scheduled-tasks-orb"
          , "pbrisbin/heroku-container-orb"
          , "pbrisbin/docker-build-cached-orb"
          , "pbrisbin/basil"
          , "pbrisbin/okta-aws-cli-assume-role"
          , "pbrisbin/vim-mkdir"
          , "pbrisbin/wat"
          , "pbrisbin/codeclimate-gnu-complexity"
          , "pbrisbin/get-netrc"
          , "pbrisbin/vim-syntax-shakespeare"
          , "pbrisbin/stack-templates"
          , "pbrisbin/google-contacts"
          , "pbrisbin/heredoc"
          , "pbrisbin/haskell-jwt"
          , "pbrisbin/console-prompt"
          , "pbrisbin/pushover-client"
          , "pbrisbin/vim-compiler-stack"
          , "pbrisbin/vim-cram"
          , "pbrisbin/resume"
          , "pbrisbin/pass-ui"
          , "pbrisbin/oss-guidelines-check"
          , "pbrisbin/liquid"
          , "pbrisbin/heroku-build"
          , "pbrisbin/dagoba"
          , "pbrisbin/raw-audio"
          , "pbrisbin/docker-static-hs"
          , "pbrisbin/gh-pocket-knife"
          , "pbrisbin/Scout2-json"
          , "pbrisbin/drafts"
          , "pbrisbin/cis194"
          , "pbrisbin/cabal-test-hunit"
          , "pbrisbin/docker-heroku-haskell-stack"
          , "pbrisbin/docker-deluge"
          , "pbrisbin/docker-openvpn-proxy"
          , "pbrisbin/vim-runfile"
          , "pbrisbin/google-drive"
          , "pbrisbin/heroku-client-standalone"
          , "pbrisbin/kramdown-man"
          , "pbrisbin/mini-tweet"
          , "pbrisbin/authenticate-oauth-cli"
          , "pbrisbin/pkgbuilds"
          , "pbrisbin/docker-halcyon"
          , "pbrisbin/fugitive-bug"
          , "pbrisbin/ex-lint"
          , "pbrisbin/ghu"
          , "pbrisbin/hgdata"
          , "pbrisbin/mkmnfst"
          , "pbrisbin/yesod-comments"
          , "pbrisbin/vim-alt-ctags"
          , "pbrisbin/vim-rename-file"
          , "pbrisbin/vim-restore-cursor"
          , "pbrisbin/vim-hs-indent"
          , "pbrisbin/android-receiver"
          , "pbrisbin/devsite"
          , "pbrisbin/josh-scripts"
          , "pbrisbin/mvtv"
          , "pbrisbin/yesod-minimal"
          , "pbrisbin/pacruft"
          , "pbrisbin/rcm2"
          , "pbrisbin/zsh-config"
          , "pbrisbin/yak"
          , "pbrisbin/liquid-cli"
          , "pbrisbin/go-euler"
          , "pbrisbin/vim-config"
          , "pbrisbin/scripts"
          , "pbrisbin/tracker-site"
          , "pbrisbin/tracker"
          , "pbrisbin/cruft"
          , "pbrisbin/rdin"
          , "pbrisbin/yesod-links"
          , "pbrisbin/aggregate_root"
          , "pbrisbin/edir"
          , "pbrisbin/screen-config"
          , "pbrisbin/airs"
          , "pbrisbin/raury"
          , "pbrisbin/paur"
          , "pbrisbin/cliff"
          , "pbrisbin/lemonstand"
          , "pbrisbin/dvdcopy"
          , "pbrisbin/bandit"
          , "pbrisbin/yesod-goodies"
          , "pbrisbin/s3-utils"
          , "pbrisbin/wifi-pipe"
          , "pbrisbin/rabbit"
          , "pbrisbin/albumart"
          , "pbrisbin/yago"
          , "pbrisbin/yesod-mpc"
          , "pbrisbin/irssi-scripts"
          , "pbrisbin/yesod-newsfeed"
          , "pbrisbin/yesod-statistics"
          , "pbrisbin/parking-awesome"
          ]
