name: CI

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: stack
        uses: freckle/stack-action@v5

      # https://github.com/ocharles/weeder/issues/190
      # - uses: freckle/weeder-action@v2
      #   with:
      #     ghc-version: ${{ steps.stack.outputs.compiler-version }}

      - uses: actions/upload-artifact@v4
        with:
          path: ${{ steps.stack.outputs.local-install-root }}/bin/ghctl
          if-no-files-found: error

  test-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binaries

      - name: Install ghctl
        run: |
          chmod +x ghctl
          sudo mv -v ghctl /usr/local/bin

      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            repositories.yaml
          sparse-checkout-cone-mode: false

      - name: Assert no differences in ghctl-plan
        run: ghctl plan --fail-on-diff
        env:
          LOG_BREAKPOINT: 200
          LOG_COLOR: always

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/hlint-setup@v2
      - uses: haskell-actions/hlint-run@v2
        with:
          fail-on: warning
